# Generated by Django 5.1.6 on 2025-03-04 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('payment_method', models.CharField(choices=[('POLARIS', 'Polaris Bank'), ('ACCESS', 'Access Bank'), ('FIDELITY', 'Fidelity'), ('GT', 'GT Bank'), ('FIRST', 'First Bank')], max_length=20)),
                ('delivery_date', models.DateField()),
                ('current_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PAID_AND_SUPPLY', 'PAID AND SUPPLY'), ('PAID', 'PAID')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RentedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
        ),
    ]
