# Generated by Django 5.1.6 on 2025-03-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renteditem',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
