# Generated by Django 5.1.6 on 2025-03-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_renteditem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renteditem',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
